### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by muneeronline97** [rayandasoriya/examstudy#1]
Dear
when I am try to login on local server is always shows login error message while I am use correct user name and password so please tell me how to solve this issue

**Comment by rayandasoriya** [comment]
You need to run the Database/exam_system.sql file on phpMyAdmin to setup the database in your machine. Then modify the configurations in the db_config file. Once done, I hope that the things will work for you. The link mentioned in the readme section is broken due to some TTL settings provided by the server but the projects runs fine on localhost.
